package au.com.commbank.weathergenerator.forecast;

import java.util.Date;

import au.com.commbank.weathergenerator.Condition;
import au.com.commbank.weathergenerator.Position;
import au.com.commbank.weathergenerator.Weather;

/**
 * This class is responsible to populate weather objects with the prediction of
 * each of its properties generated by an appropriate predictor.
 * 
 * @author leandropadua
 *
 */
public class WeatherForecaster {

	/**
	 * Given the position and date, it populate weather objects with the
	 * prediction of each of its properties generated by an appropriate
	 * predictor.
	 * 
	 * @param position
	 * @param date
	 * @return the predicted weather.
	 */
	public Weather forecast(Position position, Date date) {
		Double temperature = TemperaturePredictor.predict(position, date);
		double pressure = PressurePredictor.predict(position.getElevation());
		int humidity = HumidityPredictor.predict(pressure, temperature);
		Condition condition = ConditionPredictor.predict(humidity, temperature);
		return new Weather("", position, date, condition, temperature, pressure, humidity);
	}
}
